import jsPDF from 'jspdf';

interface ServiceItem {
  sequence: number;
  type: string;
  title: string | null;
  ccliNumber?: string | null;
  scriptureRef?: string | null;
  speaker?: string | null;
  duration?: number | null;
  notes?: string | null;
}

interface BulletinData {
  serviceDate: Date | string;
  items: ServiceItem[];
  churchName?: string;
}

export function generateBulletinPDF(bulletinData: BulletinData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Church name
  const churchName = bulletinData.churchName || 'Grace Community Church';
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(churchName, pageWidth / 2, yPos, { align: 'center' });

  yPos += 15;

  // Service date
  const serviceDate = new Date(bulletinData.serviceDate);
  const formattedDate = serviceDate.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(formattedDate, pageWidth / 2, yPos, { align: 'center' });

  yPos += 20;

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Order of Worship', pageWidth / 2, yPos, { align: 'center' });

  yPos += 15;

  // Service items
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  bulletinData.items.forEach((item) => {
    // Check if we need a new page
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }

    // Item type (right aligned)
    doc.setFont('helvetica', 'bold');
    doc.text(item.type, 20, yPos);

    // Item title (centered/main)
    doc.setFont('helvetica', 'normal');
    const title = item.title || 'Untitled';
    doc.text(title, 70, yPos);

    yPos += 7;

    // Additional details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');

    if (item.ccliNumber) {
      doc.text(`CCLI #${item.ccliNumber}`, 70, yPos);
      yPos += 5;
    }

    if (item.scriptureRef) {
      doc.text(item.scriptureRef, 70, yPos);
      yPos += 5;
    }

    if (item.speaker) {
      doc.text(`Speaker: ${item.speaker}`, 70, yPos);
      yPos += 5;
    }

    if (item.duration) {
      doc.text(`(${item.duration} min)`, 70, yPos);
      yPos += 5;
    }

    // Reset font
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');

    yPos += 8;
  });

  // Footer
  yPos = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Elder-First Church Platform', pageWidth / 2, yPos, { align: 'center' });

  // Generate filename
  const filename = `bulletin-${serviceDate.toISOString().split('T')[0]}.pdf`;

  // Download
  doc.save(filename);
}
