'use client';

import { useState, useCallback } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Card, CardContent } from '@/components/ui/Card';
import {
  Trash2,
  ChevronUp,
  ChevronDown,
  Download,
  Copy,
  Check,
  BookOpen,
  Music,
  FileText,
  StickyNote,
  Folder,
} from 'lucide-react';
import type { SermonElement } from '@elder-first/types';

interface SermonHelperOutlineProps {
  elements: SermonElement[];
  onElementsChange: (elements: SermonElement[]) => void;
  sermonTitle: string;
}

/**
 * Generate a simple UUID for client-side element IDs
 */
function generateId(): string {
  return crypto.randomUUID();
}

/**
 * Get icon for element type
 */
function getElementIcon(type: SermonElement['type']) {
  switch (type) {
    case 'section':
      return <Folder size={16} className="text-purple-600" />;
    case 'point':
      return <FileText size={16} className="text-blue-600" />;
    case 'note':
      return <StickyNote size={16} className="text-gray-600" />;
    case 'scripture':
      return <BookOpen size={16} className="text-amber-600" />;
    case 'hymn':
      return <Music size={16} className="text-green-600" />;
    default:
      return <FileText size={16} />;
  }
}

/**
 * Get label for element type
 */
function getElementLabel(type: SermonElement['type']): string {
  switch (type) {
    case 'section':
      return 'Section';
    case 'point':
      return 'Point';
    case 'note':
      return 'Note';
    case 'scripture':
      return 'Scripture';
    case 'hymn':
      return 'Hymn';
    default:
      return 'Element';
  }
}

/**
 * Export outline to Markdown format
 */
function exportToMarkdown(elements: SermonElement[], sermonTitle: string): string {
  let md = `# ${sermonTitle}\n\n`;
  md += `## Sermon Outline\n\n`;

  for (const el of elements) {
    switch (el.type) {
      case 'section':
        md += `### ${el.title}\n\n`;
        break;
      case 'point':
        md += `- **Point:** ${el.text}\n`;
        break;
      case 'note':
        md += `- *Note:* ${el.text}\n`;
        break;
      case 'scripture':
        md += `- **Scripture:** ${el.reference}`;
        if (el.note) md += ` — ${el.note}`;
        md += '\n';
        break;
      case 'hymn':
        md += `- **Hymn:** ${el.title}`;
        if (el.note) md += ` — ${el.note}`;
        md += '\n';
        break;
    }
  }

  md += '\n---\n*Generated by Elder-First Church Platform*\n';
  return md;
}

export function SermonHelperOutline({
  elements,
  onElementsChange,
  sermonTitle,
}: SermonHelperOutlineProps) {
  const [copied, setCopied] = useState(false);

  // Add a new element of specified type
  const addElement = useCallback(
    (type: SermonElement['type']) => {
      let newElement: SermonElement;

      switch (type) {
        case 'section':
          newElement = { id: generateId(), type: 'section', title: '' };
          break;
        case 'point':
          newElement = { id: generateId(), type: 'point', text: '' };
          break;
        case 'note':
          newElement = { id: generateId(), type: 'note', text: '' };
          break;
        case 'scripture':
          newElement = { id: generateId(), type: 'scripture', reference: '', note: '' };
          break;
        case 'hymn':
          // Hymns are typically added via the Hymn Finder, but allow manual add
          newElement = { id: generateId(), type: 'hymn', hymnId: generateId(), title: '', note: '' };
          break;
        default:
          return;
      }

      onElementsChange([...elements, newElement]);
    },
    [elements, onElementsChange]
  );

  // Update an element
  const updateElement = useCallback(
    (id: string, updates: Record<string, unknown>) => {
      onElementsChange(
        elements.map((el) =>
          el.id === id ? ({ ...el, ...updates } as SermonElement) : el
        )
      );
    },
    [elements, onElementsChange]
  );

  // Delete an element
  const deleteElement = useCallback(
    (id: string) => {
      onElementsChange(elements.filter((el) => el.id !== id));
    },
    [elements, onElementsChange]
  );

  // Move element up
  const moveUp = useCallback(
    (index: number) => {
      if (index === 0) return;
      const newElements = [...elements];
      [newElements[index - 1], newElements[index]] = [newElements[index], newElements[index - 1]];
      onElementsChange(newElements);
    },
    [elements, onElementsChange]
  );

  // Move element down
  const moveDown = useCallback(
    (index: number) => {
      if (index === elements.length - 1) return;
      const newElements = [...elements];
      [newElements[index], newElements[index + 1]] = [newElements[index + 1], newElements[index]];
      onElementsChange(newElements);
    },
    [elements, onElementsChange]
  );

  // Export to clipboard
  const copyToClipboard = useCallback(async () => {
    const markdown = exportToMarkdown(elements, sermonTitle);
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [elements, sermonTitle]);

  // Export as file download
  const downloadMarkdown = useCallback(() => {
    const markdown = exportToMarkdown(elements, sermonTitle);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${sermonTitle.replace(/[^a-zA-Z0-9]/g, '_')}_outline.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [elements, sermonTitle]);

  return (
    <div className="space-y-4">
      {/* Add Element Buttons */}
      <div className="flex flex-wrap gap-2">
        <Button variant="outline" size="sm" onClick={() => addElement('section')} className="gap-1">
          <Folder size={14} /> Section
        </Button>
        <Button variant="outline" size="sm" onClick={() => addElement('point')} className="gap-1">
          <FileText size={14} /> Point
        </Button>
        <Button variant="outline" size="sm" onClick={() => addElement('note')} className="gap-1">
          <StickyNote size={14} /> Note
        </Button>
        <Button variant="outline" size="sm" onClick={() => addElement('scripture')} className="gap-1">
          <BookOpen size={14} /> Scripture
        </Button>
      </div>

      {/* Elements List */}
      <div className="space-y-2">
        {elements.length === 0 ? (
          <div className="text-center py-8 text-gray-500 border border-dashed rounded-lg">
            <p className="text-base">No outline elements yet.</p>
            <p className="text-sm mt-1">
              Add elements above or use AI Suggestions to get started.
            </p>
          </div>
        ) : (
          elements.map((element, index) => (
            <Card key={element.id} variant="outlined" className="relative">
              <CardContent className="py-3 px-4">
                <div className="flex items-start gap-3">
                  {/* Icon & Type Label */}
                  <div className="flex items-center gap-2 min-w-[100px]">
                    {getElementIcon(element.type)}
                    <span className="text-sm font-medium text-gray-600">
                      {getElementLabel(element.type)}
                    </span>
                  </div>

                  {/* Editable Content */}
                  <div className="flex-1">
                    {element.type === 'section' && (
                      <Input
                        value={element.title}
                        onChange={(e) => updateElement(element.id, { title: e.target.value })}
                        placeholder="Section title..."
                        className="font-semibold"
                      />
                    )}
                    {element.type === 'point' && (
                      <Input
                        value={element.text}
                        onChange={(e) => updateElement(element.id, { text: e.target.value })}
                        placeholder="Main point text..."
                      />
                    )}
                    {element.type === 'note' && (
                      <Input
                        value={element.text}
                        onChange={(e) => updateElement(element.id, { text: e.target.value })}
                        placeholder="Note text..."
                      />
                    )}
                    {element.type === 'scripture' && (
                      <div className="space-y-2">
                        <Input
                          value={element.reference}
                          onChange={(e) => updateElement(element.id, { reference: e.target.value })}
                          placeholder="e.g., John 3:16-18"
                          className="font-medium"
                        />
                        <Input
                          value={element.note || ''}
                          onChange={(e) => updateElement(element.id, { note: e.target.value })}
                          placeholder="Optional note..."
                          className="text-sm"
                        />
                      </div>
                    )}
                    {element.type === 'hymn' && (
                      <div className="space-y-2">
                        <div className="text-base font-medium">{element.title || 'Untitled Hymn'}</div>
                        <Input
                          value={element.note || ''}
                          onChange={(e) => updateElement(element.id, { note: e.target.value })}
                          placeholder="Optional note (e.g., verses to sing)..."
                          className="text-sm"
                        />
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => moveUp(index)}
                      disabled={index === 0}
                      className="p-1 hover:bg-gray-100 rounded disabled:opacity-50"
                      title="Move up"
                    >
                      <ChevronUp size={16} />
                    </button>
                    <button
                      type="button"
                      onClick={() => moveDown(index)}
                      disabled={index === elements.length - 1}
                      className="p-1 hover:bg-gray-100 rounded disabled:opacity-50"
                      title="Move down"
                    >
                      <ChevronDown size={16} />
                    </button>
                    <button
                      type="button"
                      onClick={() => deleteElement(element.id)}
                      className="p-1 text-red-600 hover:text-red-700 hover:bg-red-50 rounded"
                      title="Delete"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* Export Buttons */}
      {elements.length > 0 && (
        <div className="flex gap-2 pt-4 border-t">
          <Button variant="outline" size="sm" onClick={copyToClipboard} className="gap-2">
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </Button>
          <Button variant="outline" size="sm" onClick={downloadMarkdown} className="gap-2">
            <Download size={14} /> Download Markdown
          </Button>
        </div>
      )}
    </div>
  );
}
