# ============================================================================
# Elder-First Church Platform - GitHub Actions CI/CD Pipelines
# Version: 1.0
# ============================================================================

# This file contains GitHub Actions workflows for continuous integration
# and deployment to Azure. Includes OIDC authentication (no secrets needed).

# ============================================================================
# Workflow 1: CI - Pull Request Validation
# ============================================================================

name: CI - Pull Request

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8.x'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript check
        run: pnpm tsc --noEmit

      - name: Run unit tests
        run: pnpm test:unit --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json

  build:
    name: Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build
        env:
          NEXT_PUBLIC_APP_ENV: staging

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .next/
          retention-days: 7

  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          TEST_BASE_URL: http://localhost:3000

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

# ============================================================================
# Workflow 2: CD - Deploy to Staging (on push to develop)
# ============================================================================

name: CD - Deploy to Staging

on:
  push:
    branches: [develop]

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8.x'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy to Staging
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: staging
      url: https://staging.elderfirst.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          NEXT_PUBLIC_APP_ENV: staging
          NEXT_PUBLIC_API_URL: https://api-staging.elderfirst.app

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-vrd-202545-stg-eus2-01
          slot-name: production
          package: .

      - name: Run database migrations
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}

      - name: Warm up application
        run: curl -f https://staging.elderfirst.app/api/health || exit 1

  deploy-container-apps:
    name: Deploy Render Service (Container App)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build-and-deploy
    environment:
      name: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/render
          file: ./services/render/Dockerfile
          push: true
          tags: |
            acrvrd202545stgeus201.azurecr.io/render-service:${{ github.sha }}
            acrvrd202545stgeus201.azurecr.io/render-service:latest

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name ca-vrd-202545-stg-eus2-render-01 \
            --resource-group rg-vrd-202545-stg-eus2-app \
            --image acrvrd202545stgeus201.azurecr.io/render-service:${{ github.sha }}

# ============================================================================
# Workflow 3: CD - Deploy to Production (on push to main)
# ============================================================================

name: CD - Deploy to Production

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8.x'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy to Production (Blue/Green)
    runs-on: ubuntu-latest
    timeout-minutes: 40
    environment:
      name: production
      url: https://app.elderfirst.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          NEXT_PUBLIC_APP_ENV: production
          NEXT_PUBLIC_API_URL: https://api.elderfirst.com

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      # Blue/Green Deployment: Deploy to staging slot first
      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-vrd-202545-prd-eus2-01
          slot-name: staging
          package: .

      - name: Run smoke tests on staging slot
        run: |
          curl -f https://app-vrd-202545-prd-eus2-01-staging.azurewebsites.net/api/health || exit 1

      - name: Run database migrations (production)
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}

      # Swap staging slot to production
      - name: Swap slots (Blue/Green)
        run: |
          az webapp deployment slot swap \
            --resource-group rg-vrd-202545-prd-eus2-app \
            --name app-vrd-202545-prd-eus2-01 \
            --slot staging \
            --target-slot production

      - name: Verify production deployment
        run: curl -f https://app.elderfirst.com/api/health || exit 1

      - name: Notify deployment success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "✅ Production deployment successful",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production Deployment Successful*\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# ============================================================================
# Workflow 4: Infrastructure - Deploy Bicep Templates
# ============================================================================

name: Infrastructure - Deploy Bicep

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/bicep/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  validate-bicep:
    name: Validate Bicep Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep
        run: |
          az bicep build --file infrastructure/bicep/main.bicep

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: validate-bicep
    environment:
      name: ${{ github.event.inputs.environment || 'prd' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        run: |
          az deployment sub create \
            --location eastus2 \
            --template-file infrastructure/bicep/main.bicep \
            --parameters infrastructure/bicep/environments/${{ github.event.inputs.environment || 'prd' }}.parameters.json \
            --name deploy-${{ github.run_number }}

# ============================================================================
# Workflow 5: Daily Cost Report
# ============================================================================

name: Daily - Azure Cost Report

on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC daily
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  cost-report:
    name: Generate Cost Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Get Azure costs
        id: costs
        run: |
          COST=$(az consumption usage list \
            --start-date $(date -d '1 day ago' +%Y-%m-%d) \
            --end-date $(date +%Y-%m-%d) \
            --query "[?tags.Project=='202545'].{cost: pretaxCost}" \
            --output tsv | awk '{sum += $1} END {print sum}')
          echo "daily_cost=$COST" >> $GITHUB_OUTPUT

      - name: Send cost alert
        if: steps.costs.outputs.daily_cost > 50
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "⚠️ Daily cost exceeded $50",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Azure Cost Alert*\nDaily cost: $$${{ steps.costs.outputs.daily_cost }}\nThreshold: $50"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# ============================================================================
# Workflow 6: Security - Dependency Scanning
# ============================================================================

name: Security - Dependency Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run npm audit
        run: npm audit --audit-level=high

# ============================================================================
# Notes
# ============================================================================

# OIDC Setup (one-time):
# 1. Azure Portal → Azure Active Directory → App Registrations
# 2. Create app: "github-actions-oidc"
# 3. Federated credentials → Add GitHub credentials
#    - Organization: <your-org>
#    - Repository: <your-repo>
#    - Entity: Branch (main, develop)
# 4. Assign "Contributor" role to subscription
# 5. Add secrets to GitHub:
#    - AZURE_SUBSCRIPTION_ID
#    - AZURE_TENANT_ID
#    - AZURE_CLIENT_ID

# Secrets Required:
# - AZURE_SUBSCRIPTION_ID
# - AZURE_TENANT_ID
# - AZURE_CLIENT_ID (for OIDC)
# - DATABASE_URL_STAGING
# - DATABASE_URL_PRODUCTION
# - SLACK_WEBHOOK_URL (optional, for notifications)
# - CODECOV_TOKEN (optional, for coverage)
